package com.iflytek.autofly.mvpframe.greendao;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import java.util.Map;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig albumRecordDaoConfig;

    private final AlbumRecordDao albumRecordDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        albumRecordDaoConfig = daoConfigMap.get(AlbumRecordDao.class).clone();
        albumRecordDaoConfig.initIdentityScope(type);

        albumRecordDao = new AlbumRecordDao(albumRecordDaoConfig, this);

        registerDao(AlbumRecord.class, albumRecordDao);
    }
    
    public void clear() {
        albumRecordDaoConfig.clearIdentityScope();
    }

    public AlbumRecordDao getAlbumRecordDao() {
        return albumRecordDao;
    }

}
